### ISSUE TITLE
Manual reboot is needed after first start

### ISSUE THREAD

**Issue by vsapronov** [syncloud/image#47]
Symptoms:
Avahi is working - device is discoverable on Adnroid
ssh is not working - when device discovered only IP address is displayed - no id info

It could be because of broken systemd. These are messages from non successful boot:
Mar  3 20:43:59 Cubian kernel: [   20.610754] sunxi_emac sunxi_emac.0: eth0: link up, 100Mbps, full-duplex, lpa 0xCDE1
Mar  3 20:43:59 Cubian systemd-logind[479]: New seat seat0.
Mar  3 20:44:00 Cubian systemd[1]: mysql.service: control process exited, code=exited status=1
Mar  3 20:44:00 Cubian systemd[1]: Unit mysql.service entered failed state.
Mar  3 20:44:00 Cubian systemd[1]: RequestName() failed: Access denied
Mar  4 03:50:57 Cubian kernel: [   55.310617] sunxi-rtc sunxi-rtc: actually set time to 2015-3-4 3:50:57
Mar  4 03:51:13 Cubian systemd[1]: udisks.service: main process exited, code=exited, status=1
Mar  4 03:51:13 Cubian systemd[1]: Unit udisks.service entered failed state.
Mar  4 03:51:38 Cubian systemd[1]: console-kit-daemon.service: main process exited, code=exited, status=1
Mar  4 03:51:39 Cubian systemd[1]: Unit console-kit-daemon.service entered failed state.
Mar  4 03:51:39 Cubian systemd[1]: Startup finished in 16s 172ms 635us (kernel) + 1min 20s 648ms 590us (userspace) = 1min 36s 821ms 225us.

**Comment by vsapronov** [comment]
I can't reproduce this problem on Cubian X1. Closing for now.

**Comment by cyberb** [comment]
Have this issue on my new odroid-debian image on first boot after installing systemd.
Reboot fixes it.
Probably this issue: https://bugs.launchpad.net/ubuntu/+source/systemd-shim/+bug/1359439

**Comment by vsapronov** [comment]
OK, I reopened this issue.

**Comment by cyberb** [comment]
Raspberry build is not affected by this.
Odroid had many non-related reasons for this to happen. 
Closing for now.
