### ISSUE TITLE
Evaluate single-jumbo package approach

### ISSUE THREAD

**Issue by vsapronov** [syncloud/image#52]
As we discussed there are few benefits in developments of syncloud as a single jumbo package. No dependencies management, one pip deployment, one git repo....

**Comment by vsapronov** [comment]
I was thinking that we could start this NOT even from all apps, but just core:
insider, image-base, image-boot, sam, remote, apache, server - these are essentially parts of syncloud PLATFORM.
While these: owncloud, gitbucket, image-ci are real apps and could be even not installed at all. And these  are producing zero dependencies mess. There have only one dependency, like: owncloud -> PLATFORM 0.8 (or 0.7 or whatever). They shouldn't depend on each other... What do you think?

**Comment by cyberb** [comment]
Really good start.

**Comment by cyberb** [comment]
platform is merged to 0.8
